[build]
  # Build from the client subdirectory
  base = "client"
  command = "npm run build"
  publish = "dist"

# SPA fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
